# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [1]:
import numpy as np
import pandas as pd
import requests
import xlsxwriter
import math
from scipy.stats import percentileofscore as score
#for percentile scores

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding. Make sure the `.csv` file is still in your working directory and import it with the following command:

In [2]:
stocks = pd.read_csv('sp_500_stocks.csv')
IEX_CLOUD_API_TOKEN = 'Tpk_059b97af715d417d9f49f50b51b1c448'

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [3]:
symbol = 'AAPL'
useless = 'quote?'
api_url = f'https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}'
data = requests.get(api_url).json()
data

{'companyName': 'Apple Inc',
 'marketcap': 2723415645852,
 'week52high': 190.4,
 'week52low': 116.63,
 'week52highSplitAdjustOnly': 186.59,
 'week52lowSplitAdjustOnly': 118.91,
 'week52change': 0.18360514884534654,
 'sharesOutstanding': 16766996492,
 'float': 0,
 'avg10Volume': 101041668,
 'avg30Volume': 88492575,
 'day200MovingAvg': 160.4,
 'day50MovingAvg': 179.38,
 'employees': 147284,
 'ttmEPS': 11.55,
 'ttmDividendRate': 0.8822175995905379,
 'dividendYield': 0.005495710449147369,
 'nextDividendDate': '',
 'exDividendDate': '2021-10-27',
 'nextEarningsDate': '2022-01-24',
 'peRatio': 14.49397321795745,
 'beta': 1.3317266054340482,
 'maxChangePercent': 64.20277277375062,
 'year5ChangePercent': 4.8580827587863,
 'year2ChangePercent': 1.0678100007248301,
 'year1ChangePercent': 0.1792709058402587,
 'ytdChangePercent': -0.08963650429609482,
 'month6ChangePercent': 0.10048247774101046,
 'month3ChangePercent': 0.09416117469375665,
 'month1ChangePercent': -0.08042986654989114,
 'day30ChangePercent': -0.08129375617132396,
 'day5ChangePercent': -0.0643049419132187}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [4]:
data['year1ChangePercent']

0.1792709058402587

## Executing A Batch API Call & Building Our DataFrame

Just like in our first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [5]:
# Function sourced from 
# https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#     print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [6]:
final_dataframe = pd.DataFrame(columns = my_columns)
#final_dataframe
for symbol_string in symbol_strings:
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        if symbol == 'WLTW':
            continue
        final_dataframe = final_dataframe.append(
        pd.Series(
        [
            symbol,
            data[symbol]['price'],
            data[symbol]['stats']['year1ChangePercent'],
            'N/A'
        ],
            index = my_columns
            
        ),
            ignore_index=True
        )
        
#final_dataframe

In [7]:
final_dataframe.head()

  Ticker   Price One-Year Price Return Number of Shares to Buy
0      A  140.93             0.0984724                     N/A
1    AAL   17.17             0.0314533                     N/A
2    AAP  241.43              0.403087                     N/A
3   AAPL  162.48              0.180866                     N/A
4   ABBV  137.94              0.251664                     N/A

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [8]:
final_dataframe.sort_values('One-Year Price Return', ascending = False, inplace = True)
final_dataframe = final_dataframe[:50]
final_dataframe.reset_index(inplace = True)
final_dataframe.head()

   index Ticker  Price One-Year Price Return Number of Shares to Buy
0    275     LB  81.13               2.32036                     N/A
1    148    DVN  48.45               1.80008                     N/A
2    317    MRO  18.60               1.26242                     N/A
3    109    COP  84.80                1.0438                     N/A
4    299   MCHP  76.22              0.981971                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [9]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input('Enter the size of the portfolio: ')
    
    try:
        float(portfolio_size)
    except:
        print('That is not a number!')
        print('Try Again')
        portfolio_size = input('Enter the size of the portfolio: ')
    
portfolio_input()
print(portfolio_size)

Enter the size of the portfolio: 10000000
10000000

In [10]:
position_size = float(portfolio_size)/len(final_dataframe.index)
for i in range(0, len(final_dataframe)):
    final_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/final_dataframe.loc[i, 'Price'])
#final_dataframe

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [11]:
hqm_columns = [
                'Ticker', 
                'Price', 
                'Number of Shares to Buy', 
                'One-Year Price Return', 
                'One-Year Return Percentile',
                'Six-Month Price Return',
                'Six-Month Return Percentile',
                'Three-Month Price Return',
                'Three-Month Return Percentile',
                'One-Month Price Return',
                'One-Month Return Percentile',
                'HQM Score'
                ]
hqm_dataframe = pd.DataFrame(columns = hqm_columns)

for symbol_string in symbol_strings:
#     print(symbol_strings)
    batch_api_call_url = f'https://sandbox.iexapis.com/stable/stock/market/batch/?types=stats,quote&symbols={symbol_string}&token={IEX_CLOUD_API_TOKEN}'
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(','):
        if symbol == 'WLTW' : continue
        hqm_dataframe = hqm_dataframe.append(
                                        pd.Series([symbol, 
                                                   data[symbol]['quote']['latestPrice'],
                                                   'N/A',
                                                   data[symbol]['stats']['year1ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month6ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month3ChangePercent'],
                                                   'N/A',
                                                   data[symbol]['stats']['month1ChangePercent'],
                                                   'N/A',
                                                   'N/A'
                                                   ], 
                                                  index = hqm_columns), 
                                        ignore_index = True)
hqm_dataframe.replace(to_replace=[None], value=0, inplace=True)

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [12]:
time_periods = [
                'One-Year',
                'Six-Month',
                'Three-Month',
                'One-Month'
                ]
#print(hqm_dataframe.columns)

for row in hqm_dataframe.index:
    for time_period in time_periods:
        change_col = f'{time_period} Price Return'
        percentile_col = f'{time_period} Return Percentile'

        hqm_dataframe.loc[row, percentile_col] = score(hqm_dataframe[change_col], hqm_dataframe.loc[row, change_col])/100

        #print(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
hqm_dataframe

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,138.44,N/A,0.097901,0.373016,-0.095294,0.206349,-0.134574,0.134921,-0.129824,0.140873,N/A
1,AAL,16.67,N/A,0.030979,0.253968,-0.237704,0.0416667,-0.149712,0.109127,-0.107699,0.214286,N/A
2,AAP,242.26,N/A,0.403677,0.847222,0.062509,0.630952,-0.021681,0.496032,-0.027025,0.505952,N/A
3,AAPL,164.27,N/A,0.183507,0.527778,0.097152,0.738095,0.097153,0.875,-0.081476,0.309524,N/A
4,ABBV,136.43,N/A,0.252037,0.646825,0.144246,0.821429,0.224933,0.982143,0.002039,0.646825,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
499,YUM,131.33,N/A,0.180821,0.521825,0.019945,0.503968,-0.014863,0.521825,-0.085380,0.293651,N/A
500,ZBH,124.47,N/A,-0.245862,0.0277778,-0.242169,0.0297619,-0.193199,0.0595238,-0.036506,0.482143,N/A
501,ZBRA,509.85,N/A,0.214978,0.59127,-0.099238,0.198413,-0.065320,0.31746,-0.157463,0.077381,N/A
502,ZION,64.69,N/A,0.331243,0.757937,0.235160,0.928571,-0.066629,0.313492,-0.009838,0.583333,N/A
503,ZTS,208.80,N/A,0.239162,0.625,-0.013663,0.416667,-0.036712,0.452381,-0.173640,0.0575397,N/A

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [13]:
from statistics import mean

for row in hqm_dataframe.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_dataframe.loc[row, f'{time_period} Return Percentile'])
    #print(momentum_percentiles)
    hqm_dataframe.loc[row, 'HQM Score'] = mean(momentum_percentiles)

hqm_dataframe.head()

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,A,138.44,N/A,0.097901,0.373016,-0.095294,0.206349,-0.134574,0.134921,-0.129824,0.140873,0.21379
1,AAL,16.67,N/A,0.030979,0.253968,-0.237704,0.0416667,-0.149712,0.109127,-0.107699,0.214286,0.154762
2,AAP,242.26,N/A,0.403677,0.847222,0.062509,0.630952,-0.021681,0.496032,-0.027025,0.505952,0.62004
3,AAPL,164.27,N/A,0.183507,0.527778,0.097152,0.738095,0.097153,0.875,-0.081476,0.309524,0.612599
4,ABBV,136.43,N/A,0.252037,0.646825,0.144246,0.821429,0.224933,0.982143,0.002039,0.646825,0.774306

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [14]:
hqm_dataframe.sort_values('HQM Score', ascending=False, inplace = True)
hqm_dataframe = hqm_dataframe[:50]
hqm_dataframe.reset_index(inplace = True, drop = True )

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

In [15]:
portfolio_input()

Enter the size of the portfolio: 1000000

In [16]:
position_size = float(portfolio_size)/len(hqm_dataframe.index)
#position_size
for i in hqm_dataframe.index:
    hqm_dataframe.loc[i , 'Number of Shares to Buy'] = math.floor(position_size/hqm_dataframe.loc[i , 'Price'])

hqm_dataframe.head()

C:\Users\User\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

,Ticker,Price,Number of Shares to Buy,One-Year Price Return,One-Year Return Percentile,Six-Month Price Return,Six-Month Return Percentile,Three-Month Price Return,Three-Month Return Percentile,One-Month Price Return,One-Month Return Percentile,HQM Score
0,LB,81.14,246,2.285434,1,0.828404,0.996032,0.223716,0.980159,0.081068,0.934524,0.977679
1,DVN,48.91,408,1.774603,0.998016,0.901447,0.998016,0.166096,0.954365,0.097606,0.952381,0.975694
2,EOG,106.70,187,0.943177,0.990079,0.445931,0.982143,0.129084,0.93254,0.162945,0.982143,0.971726
3,XOM,73.49,272,0.634102,0.96627,0.306252,0.956349,0.166570,0.956349,0.183893,0.990079,0.967262
4,COP,83.74,238,1.051796,0.994048,0.531805,0.988095,0.104444,0.892857,0.172611,0.986111,0.965278

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization. However, the tradeoff for this is that the library can seem very complicated to new users. Accordingly, this section will be fairly long because I want to do a good job of explaining how XlsxWriter works.

In [17]:
writer = pd.ExcelWriter('momentum_strategy.xlsx', engine = 'xlsxwriter')
hqm_dataframe.to_excel(writer, sheet_name = 'Momentum Strategy', index = False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [18]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [20]:
column_formats = {
                'A':['Ticker', string_template], 
                'B':['Price', dollar_template], 
                'C':['Number of Shares to Buy', integer_template], 
                'D':['One-Year Price Return', percent_template], 
                'E':['One-Year Return Percentile', percent_template],
                'F':['Six-Month Price Return', percent_template],
                'G':['Six-Month Return Percentile', percent_template],
                'H':['Three-Month Price Return', percent_template],
                'I':['Three-Month Return Percentile', percent_template],
                'J':['One-Month Price Return', percent_template],
                'K':['One-Month Return Percentile', percent_template],
                'L':['HQM Score', percent_template]
}


for column in column_formats.keys():
    writer.sheets['Momentum Strategy'].set_column(f'{column}:{column}' , 25, column_formats[column][1])
    writer.sheets['Momentum Strategy'].write(f'{column}1', column_formats[column][0], column_formats[column][1])
writer.save()

## Saving Our Excel Output

As before, saving our Excel output is very easy: